pipeline {
  agent {
    label {
        label "built-in"
        customWorkspace "/mnt/project/"
    }
  }
  stages {
    stage ("clear ws") {
      steps {
        sh "sudo rm -rf 24-q2"
      }
    }
    stage ("git clone branch") {
      steps {
        sh "sudo git clone https://github.com/vinodhalsangi/assigments-jenkinsfile.git 24-q2 -b 24-q2"
      }
    }
    stage (permission){
        steps {
            sh "sudo chmod -R 777 *"
        }
    }
    stage ("deploy on server") {
      steps {
        sh "sudo scp -i /mnt/key-pair/devops-kp.pem /mnt/project/24-q2/index.html ec2-user@65.0.61.189:/var/www/html/"
      }
    }
  }
}
