pipeline {
  agent {
    label {
        label "built-in"
    }
  }
  stages {
    stage (permission){
      steps {
        sh "sudo chmod -R 777 *"
      }
    }
    stage ("deploy on server") {
      steps {
        sh "sudo scp -i /mnt/key-pair/devops-kp.pem index.html ec2-user@52.66.121.101:/var/www/html/"
      }
    }
  }
}
